@url_dev=http://localhost:5000/v1/api
### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: f8547d7c3c6db4233dcdc6e2b0e5cc7d724c918886184ada4b3b5672f6b2a08b

{
    "name":"Shop eCOM2",
    "email":"admin2@gmail.com",
    "password":"123456"
}


### login
POST {{url_dev}}/shop/login
Content-Type: application/json
x-api-key: f8547d7c3c6db4233dcdc6e2b0e5cc7d724c918886184ada4b3b5672f6b2a08b

{
    "email":"admin@gmail.com",
    "password":"123456"
}

### logout
POST {{url_dev}}/shop/logout
Content-Type: application/json
x-api-key: f8547d7c3c6db4233dcdc6e2b0e5cc7d724c918886184ada4b3b5672f6b2a08b
x-client-id: 6558ab187f61b076b884dd47
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NTU4YWIxODdmNjFiMDc2Yjg4NGRkNDciLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlhdCI6MTcwMDMxMDgzNywiZXhwIjoxNzAwNDgzNjM3fQ.jZqWIv5pD4-yE1CbuAWzzaFyy3bhR1Fpmab1TQDdsLM