@url_dev=http://localhost:5000/v1/api
### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 861ecbef0e079b20afa295ed6135b98a32c341cf2c8c248f200170a33c368cac

{
    "name":"Shop eCOM10",
    "email":"admin10@gmail.com",
    "password":"123456"
}

